extern crate peg;
use aoc_helpers::AOCFileOrParseError;

#[derive(Debug, Hash, Eq, PartialEq, Copy, Clone)]
pub enum MazeTile {
    Wall,
    Room,
    Start,
    End,
}

peg::parser! { pub grammar day16_parser() for str {
    rule number() -> usize
        = n:$(['0'..='9']+) { n.parse().expect(&format!("Was expecting a number string {}", n)[..])}
    rule wall() -> MazeTile
        = "#" { MazeTile::Wall }
    rule room() -> MazeTile
        = "." { MazeTile::Room }
    rule start() -> MazeTile
        = "S" { MazeTile::Start }
    rule end() -> MazeTile
        = "E" { MazeTile::End }
    rule maze_tile() -> MazeTile
        = maze_tile:(wall() / room() / start() / end()) { maze_tile }
    rule line() -> Vec<MazeTile>
        = line:maze_tile() ++ "" { line }
    pub rule parse() -> Vec<Vec<MazeTile>>
        = lines:line() ++ "\n" "\n" * { lines }
}}

pub fn parse_data(input: &str) -> Result<Vec<Vec<MazeTile>>, AOCFileOrParseError> {
    if let Ok(ret) = day16_parser::parse(input) {
        Ok(ret)
    } else {
        Err(AOCFileOrParseError)
    }
}

#[cfg(test)]
mod test {
    use super::*;
    use pretty_assertions::assert_eq;

    use aoc_helpers::read_input_file;
    #[test]
    fn test_parse() {
        let input_str = read_input_file("data/test_data_2.txt").unwrap();
        let actual = day16_parser::parse(&input_str).expect("Should parse successfully");
        let expected: Vec<Vec<MazeTile>> = vec![
            vec![
                MazeTile::Wall,
                MazeTile::Wall,
                MazeTile::Wall,
                MazeTile::Wall,
                MazeTile::Wall,
                MazeTile::Wall,
                MazeTile::Wall,
                MazeTile::Wall,
                MazeTile::Wall,
                MazeTile::Wall,
                MazeTile::Wall,
                MazeTile::Wall,
                MazeTile::Wall,
                MazeTile::Wall,
                MazeTile::Wall,
                MazeTile::Wall,
                MazeTile::Wall,
            ],
            vec![
                MazeTile::Wall,
                MazeTile::Room,
                MazeTile::Room,
                MazeTile::Room,
                MazeTile::Wall,
                MazeTile::Room,
                MazeTile::Room,
                MazeTile::Room,
                MazeTile::Wall,
                MazeTile::Room,
                MazeTile::Room,
                MazeTile::Room,
                MazeTile::Wall,
                MazeTile::Room,
                MazeTile::Room,
                MazeTile::End,
                MazeTile::Wall,
            ],
            vec![
                MazeTile::Wall,
                MazeTile::Room,
                MazeTile::Wall,
                MazeTile::Room,
                MazeTile::Wall,
                MazeTile::Room,
                MazeTile::Wall,
                MazeTile::Room,
                MazeTile::Wall,
                MazeTile::Room,
                MazeTile::Wall,
                MazeTile::Room,
                MazeTile::Wall,
                MazeTile::Room,
                MazeTile::Wall,
                MazeTile::Room,
                MazeTile::Wall,
            ],
            vec![
                MazeTile::Wall,
                MazeTile::Room,
                MazeTile::Wall,
                MazeTile::Room,
                MazeTile::Wall,
                MazeTile::Room,
                MazeTile::Wall,
                MazeTile::Room,
                MazeTile::Room,
                MazeTile::Room,
                MazeTile::Wall,
                MazeTile::Room,
                MazeTile::Room,
                MazeTile::Room,
                MazeTile::Wall,
                MazeTile::Room,
                MazeTile::Wall,
            ],
            vec![
                MazeTile::Wall,
                MazeTile::Room,
                MazeTile::Wall,
                MazeTile::Room,
                MazeTile::Wall,
                MazeTile::Room,
                MazeTile::Wall,
                MazeTile::Room,
                MazeTile::Wall,
                MazeTile::Wall,
                MazeTile::Wall,
                MazeTile::Room,
                MazeTile::Wall,
                MazeTile::Room,
                MazeTile::Wall,
                MazeTile::Room,
                MazeTile::Wall,
            ],
            vec![
                MazeTile::Wall,
                MazeTile::Room,
                MazeTile::Room,
                MazeTile::Room,
                MazeTile::Wall,
                MazeTile::Room,
                MazeTile::Wall,
                MazeTile::Room,
                MazeTile::Wall,
                MazeTile::Room,
                MazeTile::Room,
                MazeTile::Room,
                MazeTile::Room,
                MazeTile::Room,
                MazeTile::Wall,
                MazeTile::Room,
                MazeTile::Wall,
            ],
            vec![
                MazeTile::Wall,
                MazeTile::Room,
                MazeTile::Wall,
                MazeTile::Room,
                MazeTile::Wall,
                MazeTile::Room,
                MazeTile::Wall,
                MazeTile::Room,
                MazeTile::Wall,
                MazeTile::Room,
                MazeTile::Wall,
                MazeTile::Wall,
                MazeTile::Wall,
                MazeTile::Wall,
                MazeTile::Wall,
                MazeTile::Room,
                MazeTile::Wall,
            ],
            vec![
                MazeTile::Wall,
                MazeTile::Room,
                MazeTile::Wall,
                MazeTile::Room,
                MazeTile::Room,
                MazeTile::Room,
                MazeTile::Wall,
                MazeTile::Room,
                MazeTile::Wall,
                MazeTile::Room,
                MazeTile::Wall,
                MazeTile::Room,
                MazeTile::Room,
                MazeTile::Room,
                MazeTile::Room,
                MazeTile::Room,
                MazeTile::Wall,
            ],
            vec![
                MazeTile::Wall,
                MazeTile::Room,
                MazeTile::Wall,
                MazeTile::Room,
                MazeTile::Wall,
                MazeTile::Wall,
                MazeTile::Wall,
                MazeTile::Wall,
                MazeTile::Wall,
                MazeTile::Room,
                MazeTile::Wall,
                MazeTile::Room,
                MazeTile::Wall,
                MazeTile::Wall,
                MazeTile::Wall,
                MazeTile::Room,
                MazeTile::Wall,
            ],
            vec![
                MazeTile::Wall,
                MazeTile::Room,
                MazeTile::Wall,
                MazeTile::Room,
                MazeTile::Wall,
                MazeTile::Room,
                MazeTile::Room,
                MazeTile::Room,
                MazeTile::Room,
                MazeTile::Room,
                MazeTile::Room,
                MazeTile::Room,
                MazeTile::Wall,
                MazeTile::Room,
                MazeTile::Room,
                MazeTile::Room,
                MazeTile::Wall,
            ],
            vec![
                MazeTile::Wall,
                MazeTile::Room,
                MazeTile::Wall,
                MazeTile::Room,
                MazeTile::Wall,
                MazeTile::Wall,
                MazeTile::Wall,
                MazeTile::Room,
                MazeTile::Wall,
                MazeTile::Wall,
                MazeTile::Wall,
                MazeTile::Wall,
                MazeTile::Wall,
                MazeTile::Room,
                MazeTile::Wall,
                MazeTile::Wall,
                MazeTile::Wall,
            ],
            vec![
                MazeTile::Wall,
                MazeTile::Room,
                MazeTile::Wall,
                MazeTile::Room,
                MazeTile::Wall,
                MazeTile::Room,
                MazeTile::Room,
                MazeTile::Room,
                MazeTile::Wall,
                MazeTile::Room,
                MazeTile::Room,
                MazeTile::Room,
                MazeTile::Room,
                MazeTile::Room,
                MazeTile::Wall,
                MazeTile::Room,
                MazeTile::Wall,
            ],
            vec![
                MazeTile::Wall,
                MazeTile::Room,
                MazeTile::Wall,
                MazeTile::Room,
                MazeTile::Wall,
                MazeTile::Room,
                MazeTile::Wall,
                MazeTile::Wall,
                MazeTile::Wall,
                MazeTile::Wall,
                MazeTile::Wall,
                MazeTile::Room,
                MazeTile::Wall,
                MazeTile::Wall,
                MazeTile::Wall,
                MazeTile::Room,
                MazeTile::Wall,
            ],
            vec![
                MazeTile::Wall,
                MazeTile::Room,
                MazeTile::Wall,
                MazeTile::Room,
                MazeTile::Wall,
                MazeTile::Room,
                MazeTile::Room,
                MazeTile::Room,
                MazeTile::Room,
                MazeTile::Room,
                MazeTile::Room,
                MazeTile::Room,
                MazeTile::Room,
                MazeTile::Room,
                MazeTile::Wall,
                MazeTile::Room,
                MazeTile::Wall,
            ],
            vec![
                MazeTile::Wall,
                MazeTile::Room,
                MazeTile::Wall,
                MazeTile::Room,
                MazeTile::Wall,
                MazeTile::Room,
                MazeTile::Wall,
                MazeTile::Wall,
                MazeTile::Wall,
                MazeTile::Wall,
                MazeTile::Wall,
                MazeTile::Wall,
                MazeTile::Wall,
                MazeTile::Wall,
                MazeTile::Wall,
                MazeTile::Room,
                MazeTile::Wall,
            ],
            vec![
                MazeTile::Wall,
                MazeTile::Start,
                MazeTile::Wall,
                MazeTile::Room,
                MazeTile::Room,
                MazeTile::Room,
                MazeTile::Room,
                MazeTile::Room,
                MazeTile::Room,
                MazeTile::Room,
                MazeTile::Room,
                MazeTile::Room,
                MazeTile::Room,
                MazeTile::Room,
                MazeTile::Room,
                MazeTile::Room,
                MazeTile::Wall,
            ],
            vec![
                MazeTile::Wall,
                MazeTile::Wall,
                MazeTile::Wall,
                MazeTile::Wall,
                MazeTile::Wall,
                MazeTile::Wall,
                MazeTile::Wall,
                MazeTile::Wall,
                MazeTile::Wall,
                MazeTile::Wall,
                MazeTile::Wall,
                MazeTile::Wall,
                MazeTile::Wall,
                MazeTile::Wall,
                MazeTile::Wall,
                MazeTile::Wall,
                MazeTile::Wall,
            ],
        ];
        assert_eq!(expected, actual)
    }
}
