[package]
name = "day10"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
peg = "0.8.1"
aoc_helpers = {path = "../aoc_helpers"}
color-eyre = "0.6.2"
pretty_assertions = "1.3.0"
